const $=s=>document.querySelector(s);let guide=null;
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renumber(){guide.steps.forEach((s,i)=>{s.number=i+1;s.title=s.title||`Step ${i+1}`})}
function render(){if(!guide)return;$('#guideTitle').value=guide.title||'';$('#guidePortal').textContent=(guide.portal||'portal').replaceAll('-',' ').toUpperCase();$('#stepCount').textContent=`${guide.steps.length} steps`;$('#intro').value=guide.intro||'';$('#steps').innerHTML=guide.steps.map((s,i)=>`<article class="step-card" data-id="${s.id}"><div class="step-number">${i+1}</div><div class="step-main"><div class="step-toolbar"><input class="step-title" value="${esc(s.title||`Step ${i+1}`)}"><button data-act="up" ${i===0?'disabled':''}>↑</button><button data-act="down" ${i===guide.steps.length-1?'disabled':''}>↓</button><button data-act="delete" class="danger-text">Delete</button></div><textarea class="instruction">${esc(s.instruction||'')}</textarea><div class="shot-wrap">${s.screenshot?`<img src="${s.screenshot}" alt="Step ${i+1} screenshot"><span class="click-marker" style="left:${(s.click?.x||0)}px;top:${(s.click?.y||0)}px">${i+1}</span>`:'<div class="missing-shot">No screenshot captured</div>'}</div><div class="step-meta">${esc(s.page_title||'')} · ${esc(s.element?.label||s.element?.selector||'')}</div></div></article>`).join('');}
async function save(){guide.title=$('#guideTitle').value.trim()||'Untitled Guide';guide.intro=$('#intro').value;guide.updated_at=new Date().toISOString();renumber();await chrome.runtime.sendMessage({type:'SAVE_GUIDE',guide});}
document.addEventListener('input',e=>{const card=e.target.closest?.('.step-card');if(!card)return;const s=guide.steps.find(x=>x.id===card.dataset.id);if(e.target.classList.contains('step-title'))s.title=e.target.value;if(e.target.classList.contains('instruction'))s.instruction=e.target.value});
document.addEventListener('click',async e=>{const b=e.target.closest('button[data-act]');if(!b)return;const card=b.closest('.step-card'),i=guide.steps.findIndex(x=>x.id===card.dataset.id);if(b.dataset.act==='delete')guide.steps.splice(i,1);if(b.dataset.act==='up'&&i>0)[guide.steps[i-1],guide.steps[i]]=[guide.steps[i],guide.steps[i-1]];if(b.dataset.act==='down'&&i<guide.steps.length-1)[guide.steps[i+1],guide.steps[i]]=[guide.steps[i],guide.steps[i+1]];renumber();await save();render()});
$('#save').onclick=save;$('#print').onclick=async()=>{await save();window.print()};$('#exportJson').onclick=async()=>{await save();const blob=new Blob([JSON.stringify(guide,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob);await chrome.downloads.download({url:u,filename:(guide.title||'guide').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.json',saveAs:true});setTimeout(()=>URL.revokeObjectURL(u),1000)};
(async()=>{const r=await chrome.runtime.sendMessage({type:'GET_GUIDE'});guide=r.guide||{title:'Untitled Guide',steps:[]};render()})();
