(()=>{
  if(globalThis.__S4U_GUIDE_RECORDER_V41__)return;globalThis.__S4U_GUIDE_RECORDER_V41__=true;
  const isBuilder=location.hostname.toLowerCase()==="guides.screenings4u.com";let lastSig="",lastAt=0,marker=null;
  if(isBuilder){
    window.addEventListener("message",async e=>{if(e.source!==window||e.origin!==location.origin)return;const m=e.data;if(!m||m.source!=="S4U_GUIDE_BUILDER"||!m.id)return;const ok=new Set(["AUTH_FROM_SITE","AUTH_STATUS","GET_STATE","START_RECORDING_FROM_SITE","STOP_RECORDING","OPEN_GUIDE","CLEAR_RECORDING"]);if(!ok.has(m.type))return;let response;try{response=await chrome.runtime.sendMessage({type:m.type,...(m.payload||{})})}catch(err){response={ok:false,error:err?.message||String(err)}}window.postMessage({source:"S4U_GUIDE_RECORDER",id:m.id,response},location.origin)});
    window.postMessage({source:"S4U_GUIDE_RECORDER_READY",version:"4.1.0"},location.origin);return;
  }
  const SENSITIVE='input[type="password"],input[name*="ssn" i],input[id*="ssn" i],input[name*="social" i],input[id*="social" i],input[name*="dob" i],input[id*="dob" i],input[name*="birth" i],input[id*="birth" i],input[name*="card" i],input[id*="card" i],input[name*="routing" i],input[id*="routing" i],[data-s4u-sensitive="true"]';
  const INTERACTIVE='button,a[href],input,select,textarea,label,summary,[role="button"],[role="link"],[role="menuitem"],[role="tab"],[role="checkbox"],[role="radio"],[tabindex]';
  const clean=s=>String(s||"").trim().replace(/\s+/g," ").slice(0,160);
  function label(el){const a=el.getAttribute?.("aria-label");if(a)return clean(a);const by=el.getAttribute?.("aria-labelledby");if(by){const n=document.getElementById(by);if(n?.textContent)return clean(n.textContent)}if(el.id){const l=document.querySelector('label[for="'+CSS.escape(el.id)+'"]');if(l?.textContent)return clean(l.textContent)}return clean(el.innerText||el.textContent||el.getAttribute?.("title")||el.getAttribute?.("placeholder")||el.getAttribute?.("name")||el.id||el.tagName)||el.tagName.toLowerCase()}
  function selector(el){if(el.id)return"#"+CSS.escape(el.id);const t=el.getAttribute?.("data-testid");if(t)return'[data-testid="'+CSS.escape(t)+'"]';const n=el.getAttribute?.("name");if(n)return el.tagName.toLowerCase()+'[name="'+CSS.escape(n)+'"]';return el.tagName.toLowerCase()}
  function masks(){const arr=[];document.querySelectorAll(SENSITIVE).forEach(el=>{const r=el.getBoundingClientRect();if(r.width<1||r.height<1)return;const m=document.createElement("div");Object.assign(m.style,{position:"fixed",left:r.left+"px",top:r.top+"px",width:r.width+"px",height:r.height+"px",background:"#111827",borderRadius:"5px",zIndex:"2147483646",pointerEvents:"none"});document.documentElement.appendChild(m);arr.push(m)});return()=>arr.forEach(x=>x.remove())}
  function show(n,x,y){hide();marker=document.createElement("div");marker.textContent=String(n);Object.assign(marker.style,{position:"fixed",left:Number(x)+"px",top:Number(y)+"px",transform:"translate(-50%,-50%)",width:"36px",height:"36px",borderRadius:"50%",background:"#ff6500",color:"#fff",border:"3px solid #fff",boxShadow:"0 2px 8px rgba(0,0,0,.38)",display:"flex",alignItems:"center",justifyContent:"center",font:"800 16px Arial,sans-serif",zIndex:"2147483647",pointerEvents:"none"});document.documentElement.appendChild(marker)}
  function hide(){marker?.remove();marker=null;document.getElementById("s4u-guide-capture-marker")?.remove()}
  async function send(el,event,verb="Select"){
    if(!el||el.closest?.(SENSITIVE))return null;const now=Date.now(),x=Number(event.clientX??(el.getBoundingClientRect().left+el.getBoundingClientRect().width/2)),y=Number(event.clientY??(el.getBoundingClientRect().top+el.getBoundingClientRect().height/2));const sig=[verb,selector(el),Math.round(x),Math.round(y)].join("|");if(sig===lastSig&&now-lastAt<180)return null;lastSig=sig;lastAt=now;const cleanup=masks();setTimeout(cleanup,500);
    return chrome.runtime.sendMessage({type:"RECORD_INTERACTION",title:verb+" "+label(el),instruction:verb+" "+label(el)+".",url:location.href,page_title:document.title,element:{tag:el.tagName.toLowerCase(),label:label(el),selector:selector(el),type:el.getAttribute?.("type")||null,role:el.getAttribute?.("role")||null},click:{x,y,x_pct:Math.max(0,Math.min(100,x/window.innerWidth*100)),y_pct:Math.max(0,Math.min(100,y/window.innerHeight*100)),viewport:{width:window.innerWidth,height:window.innerHeight}}});
  }
  document.addEventListener("pointerdown",e=>{if(e.button!==undefined&&e.button!==0)return;const raw=e.target instanceof Element?e.target:null;if(!raw)return;const el=raw.closest(INTERACTIVE)||raw;if(el.matches?.('select,input[type="checkbox"],input[type="radio"]'))return;send(el,e,"Select").catch(()=>{})},true);
  document.addEventListener("change",e=>{const el=e.target instanceof Element?e.target:null;if(!el)return;if(el.matches('select,input[type="checkbox"],input[type="radio"]')){const r=el.getBoundingClientRect();send(el,{clientX:r.left+r.width/2,clientY:r.top+r.height/2},el.matches('select')?"Choose":"Set").catch(()=>{})}},true);
  document.addEventListener("keydown",e=>{if(e.key!=="Enter")return;const el=e.target instanceof Element?e.target:null;if(!el||!el.matches('input,textarea,[contenteditable="true"]'))return;const r=el.getBoundingClientRect();send(el,{clientX:r.left+r.width/2,clientY:r.top+r.height/2},"Submit").catch(()=>{})},true);
  chrome.runtime.onMessage.addListener((m,_s,r)=>{if(m?.type==="RECORDER_PING")r({ok:true,loaded:true,version:"4.1.0"});if(m?.type==="RECORDER_STATE"){r({ok:true})}if(m?.type==="SHOW_CAPTURE_MARKER"){show(m.number,m.x,m.y);r({ok:true})}if(m?.type==="HIDE_CAPTURE_MARKER"){hide();r({ok:true})}});
  chrome.runtime.sendMessage({type:"RECORDER_PING_PAGE",url:location.href}).catch(()=>{});
})();
